### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by touste** [justinblaber/camera_calib#7]
Hi, I've been using your calibration toolbox for stereo systems, it works really well!
I would like to take some inspiration of your work to develop a similar package in Julia, can you specify a license for this toolbox so that I'm in the clear to what I am allowed to do with it?
Thanks!

**Comment by justinblaber** [comment]
@touste Thanks for the kind words. I think that would be great if you developed a julia version. I actually created a python/pytorch version myself a little bit ago (with neural net to detect fiducial markers; it works really well). 

Anyway, I guess an MIT license would be appropriate. TBH I don't really care what you do with the code. It was meant to be free and open for whatever people like as long as it's done in good faith (i.e. as long as they don't try to claim they wrote the toolbox or something). 

Thanks!

**Comment by touste** [comment]
Thanks! I'll try to give it a shot then even if it's probably take some time. 
Thanks again for sharing this!

**Comment by cvicenro7** [comment]
Hi @touste, 

I'm interested in using this toolbox to calibrate stereo systems too. When you used it, was it necessary to have the extra four fiducial markers on the calibration board, or you managed to just use a conventional checkerboard / circle grid?
